### PR TITLE
feat: handled internal error properly

### LINKED ISSUE #343: (rpc-server): Failed to serialize JsonRpcError
It's been happening for a long time.

During the last resharding some weird [still unresolved] issue happened on the `nearcore` regarding the hot/cold storage data transition. And some pieces of the data is missing from a Trie.

This results in an archival node responding with an error similar to

```
StorageError(MissingTrieValue(TrieStorage, 5pU46FzKxQz7wm3y4QaroG1pGFJeM9SGXFggWHXnD4JH))"
```

For some reason ReadRPC doesn't know how to serialize this error. We face this errors in those cases when we proxy requests to the native JSON RPC nodes (`query.call_function` on the `*.poolv1.near`). 

We need to somehow empower ReadRPC with the serialization abitlities around this particular error type to be more clear to the users, since it's hard to understand what does "Failed to serialize JsonRpcError` means.

### Step to reproduce

Request (HttPie)

```
http post https://archival-rpc.mainnet.near.org/ jsonrpc=2.0 id=qwe method=query params:='{                                                       
         "request_type": "call_function",
         "account_id": "astro-stakers.poolv1.near",
         "method_name": "get_accounts",
         "args_base64": "eyJmcm9tX2luZGV4IjogMCwgImxpbWl0IjogMTAwfQ==",
         "block_id": 123522710
     }'
```

The response is 

```
{
    "error": {
        "cause": {
            "info": {
                "error_message": "Failed to serialize JsonRpcError"
            },
            "name": "INTERNAL_ERROR"
        },
        "code": -32000,
        "data": "Failed to serialize JsonRpcError",
        "message": "Server error",
        "name": "INTERNAL_ERROR"
    },
    "id": "qwe",
    "jsonrpc": "2.0"
}
```

But has to be 

```
{
    "error": {
        "cause": {
            "info": {
                "error_message": "StorageError(MissingTrieValue(TrieStorage, 5pU46FzKxQz7wm3y4QaroG1pGFJeM9SGXFggWHXnD4JH))"
            },
            "name": "INTERNAL_ERROR"
        },
        "code": -32000,
        "data": "The node reached its limits. Try again later. More details: StorageError(MissingTrieValue(TrieStorage, 5pU46FzKxQz7wm3y4QaroG1pGFJeM9SGXFggWHXnD4JH))",
        "message": "Server error",
        "name": "INTERNAL_ERROR"
    },
    "id": "qwe",
    "jsonrpc": "2.0"
}
```

### PR DESCRIPTION
**Pull request by frolvanya**
Previously trait `impl<E> From<JsonRpcError<E>> for RPCError` was handling only `JsonRpcServerError::HandlerError` therefore when proxy call returned `JsonRpcServerError::InternalError` it was sending a "Failed to serialize JsonRpcError" string without any actual details

closes #343

### CODE REVIEW

**Comment by frolvanya** [comment]
@race-of-sloths

**Comment by race-of-sloths** [comment]
@frolvanya Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!
Weekly streak is on the road, smart strategy! Secure your streak with another PR!

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/frolvanya?type=bot&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/frolvanya?type=bot&theme=light">
    Shows profile picture for the author of the PR
</picture>](https://race-of-sloths.com/profile/frolvanya)


<details><summary>Current status: <i>waiting for scoring</i></summary>

We're waiting for maintainer to score this pull request with `@race-of-sloths score [0,1,2,3,5,8,13]` command. Alternatively, autoscoring [1,2] will be applied for this pull request

</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/frolvanya)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Invite contributor** `@race-of-sloths invite` to invite the contributor to participate in a race or include it, if it's already a runner.
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

**Comment by race-of-sloths** [comment]
### ❌ PR inactive
This PR has been inactive for two weeks. It's now marked as stale. 
>[!TIP]
If you think it's a mistake, you can restart the bot with `include` command to proceed 🔄

**Comment by kobayurii** [comment]
https://github.com/near/read-rpc/pull/352

**Pull request closed without merging**
