### PR TITLE
feat: added error metrics

### LINKED ISSUE #314: (rpc-server): Add error metrics
We've got a request from SRE team to add the necessary metrics to the `rpc-server` that would help to watch for the error rate in general.

I would like us to have the metric with labels to be able to break them down even more:

* RPC method name
* Error type (I think based on the `HANDLER_ERROR` like: `UNKNOWN_ACCOUNT`, `INVALID_ACCOUNT`, etc.)
* maybe, something else

The metric on the application side should be an `int`, preferably the metric's name should end with `_total` for easier Grafana integration.

### PR DESCRIPTION
**Pull request by frolvanya**
This PR is adding more metrics based on the method name and returned error type (`ParseError`, `HandlerError` or `InternalError`)

Example:
image

closes #314

### CODE REVIEW

**Comment by frolvanya** [comment]
@race-of-sloths please, include my PR in the Race

**Comment by race-of-sloths** [comment]
@frolvanya Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!
King of Sloths shakes your hand! Yellow leader's jersey is yours deservedly!

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/frolvanya?type=bot&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/frolvanya?type=bot&theme=light">
    Shows profile picture for the author of the PR
</picture>](https://race-of-sloths.com/profile/frolvanya)


<details><summary>Current status: <i>waiting for scoring</i></summary>

We're waiting for maintainer to score this pull request with `@race-of-sloths score [0,1,2,3,5,8,13]` command
</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/frolvanya)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

**Review by kobayurii — APPROVED** [review]
LGFM! Thank you!

**Comment by kobayurii** [comment]
@race-of-sloths score 3

**Comment by race-of-sloths** [comment]
### 🌟 Score recorded!

@kobayurii, thank you for scoring this pull request in the Race of Sloths!

**Pull request merged**
