### PR TITLE
feat: added support for a `version` flag

### LINKED ISSUE #287: (indexers): Ensure all the indexers respond to `--version`
### Motivation

Recently, I've upgraded the `near-state-indexer` to the newest `nearcore-1.40.0`, made the ReadRPC release and all. And after the deploy I couldn't prove the version of the `near-state-indexer` binary is the newer, because we don't support the `--version` for some reason.

### TODO:

* Make sure every indexer within the project responds to the `--version` with the most meaningful information. 
* [Ideally] the version should include both the project version (ReadRPC) and the supported `nearcore` version.

### PR DESCRIPTION
**Pull request by frolvanya**
I've added the version flag for all indexers. However, I didn't complete the part with a supported nearcore version. In order to print an information about nearcore version along with the indexer version, we need to store nearcore version in some env variable (or in .toml file). I'm not sure that this overhead is needed, but I'm more than happy to implement it, so please say if this small overhead worth it or not

closes #287

### CODE REVIEW

**Review by kobayurii — CHANGES_REQUESTED** [review]
Thank you! I left you a comment where you can find the information you need.

You can find nearcore version in the .cargo/config.toml -> NEARCORE_VERSION
Usage example: near-state-indexer/build.rs

**Comment by frolvanya** [comment]
Thanks for the info! I've added info about nearcore into the version flag. Let me know if the format is strange and should be changed. It looks like this now:
image

**Review by kobayurii — APPROVED** [review]
Greate! Thank you!

**Comment by frolvanya** [comment]
@khorolets I've added info about pkg version to the logs to all indexers

image

**Pull request merged**
